name: clippr
services:
  db:
    container_name: clippr_db
    image: postgres:alpine
    env_file:
      - ../.env.local
    environment:
      - POSTGRES_USER={DATABASE_USER}
      - POSTGRES_PASSWORD={DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: